import datetime
from typing import Dict, Any

class ListingExporter:
    """Generates verified selling proofs and markdown certificates for Linux storage devices."""

    @staticmethod
    def generate_markdown(disk: Dict[str, Any], benchmark_results: Dict[str, Any]) -> str:
        smart = disk.get("smart") or {}
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        poh = smart.get("power_on_hours")
        poh_str = f"{poh} hrs ({poh // 24} days / {poh / (24 * 365.25):.1f} yrs)" if poh else "N/A"
        temp = smart.get("temperature")
        temp_str = f"{temp} °C / {int(temp * 9/5 + 32)} °F" if temp is not None else "-- °C"

        md = f"""# 📦 Storage Health & Performance Certificate
**Verified on:** `{timestamp}` via **LinuxDisk** (CrystalDisk Suite for Linux)

---
### 🔍 Hardware Information
- **Model:** `{disk.get('model', 'Storage Device')}`
- **Serial Number:** `{disk.get('serial', 'Unknown')}`
- **Capacity:** `{disk.get('size_formatted', 'Unknown')}` ({disk.get('size_bytes', 0):,} bytes)
- **Interface:** `{smart.get('interface', disk.get('transport', 'SATA'))}`
- **Speed:** `{disk.get('rotation', '7200 RPM')}`
- **Firmware:** `{smart.get('firmware', 'Unknown')}`

---
### 🩺 Health & S.M.A.R.T. Status: **[{smart.get('health_grade', 'GOOD')} {smart.get('health_score', 100)}%]**
- **Operating Temperature:** `{temp_str}`
- **Power-On Time:** `{poh_str}`
- **Power Cycle Count:** `{smart.get('power_cycles', 'N/A')} times`
- **Reallocated Bad Sectors (ID 05):** `{smart.get('reallocated_sectors', 0)}` (0 = Perfect)
- **Pending Sectors (ID C5):** `{smart.get('pending_sectors', 0)}` (0 = Stable)
- **Uncorrectable Sectors (ID C6):** `{smart.get('uncorrectable_sectors', 0)}` (0 = Pristine)

"""
        if benchmark_results:
            md += """---
### ⚡ Unbuffered Speed Benchmark
| Test Profile | Read Speed | Write Speed | Read IOPS | Write IOPS |
| :--- | :--- | :--- | :--- | :--- |
"""
            for pid, res in benchmark_results.items():
                pname = res.get("profile", {}).get("name", pid)
                r_speed = f"{res['read_mbs']:.1f} MB/s" if res.get('read_mbs') is not None else "--"
                w_speed = f"{res['write_mbs']:.1f} MB/s" if res.get('write_mbs') is not None else "--"
                r_iops = f"{res['read_iops']:.0f} IOPS" if res.get('read_iops') is not None else "--"
                w_iops = f"{res['write_iops']:.0f} IOPS" if res.get('write_iops') is not None else "--"
                md += f"| **{pname}** | {r_speed} | {w_speed} | {r_iops} | {w_iops} |\n"
            md += "\n"

        md += """---
*Generated by LinuxDisk — Open Source CrystalDisk Suite for Ubuntu & Linux.*
"""
        return md
